### ISSUE TITLE
Example input/output files

### ISSUE THREAD

**Issue by mfcovington** [upendrak/lincRNA_pipeline#1]
Can you add small example input file(s) that can be run through the pipeline and the expected output file(s)?

**Comment by upendrak** [comment]
How can I add a sub-directory where i can put the sample files in this current repo? If i know this then i can put some samples there...

**Comment by upendrak** [comment]
Ok i figured it out and add the sample files including the output file in the samples.data folder. Let me know if you need further information

**Comment by mfcovington** [comment]
Thanks. You can close this issue now.
